//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttemptResult
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public System.DateTime AnswerTime { get; set; }
        public int AttemptId { get; set; }
        public bool IsCorrect { get; set; }
    }
}
