//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestStudentDBEntities : DbContext
    {
        public TestStudentDBEntities()
            : base("name=TestStudentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AttemptResult> AttemptResults { get; set; }
        public DbSet<AttemptResultAnswer> AttemptResultAnswers { get; set; }
        public DbSet<Question2Test> Question2Test { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<TestAttempt> TestAttempts { get; set; }
        public DbSet<TestInstance> TestInstances { get; set; }
        public DbSet<TestGradeLimit> TestGradeLimits { get; set; }
        public DbSet<Answer> Answers { get; set; }
        public DbSet<Question> Questions { get; set; }
    }
}
