//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestInstance
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int DisciplineType { get; set; }
        public string Description { get; set; }
        public bool IsCurrent { get; set; }
        public int QuestionCount { get; set; }
        public int MinuteTimeLimit { get; set; }
    }
}
