//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAttempt
    {
        public int Id { get; set; }
        public int TestId { get; set; }
        public int StudentId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public System.Guid AttemptKey { get; set; }
        public bool IsTimeIsUp { get; set; }
        public Nullable<int> Grade { get; set; }
    }
}
