//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestStudentDBEntities : DbContext
    {
        public TestStudentDBEntities()
            : base("name=TestStudentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttemptResult> AttemptResults { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<TestAttempt> TestAttempts { get; set; }
        public virtual DbSet<TestInstance> TestInstances { get; set; }
    }
}
