//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAttempt
    {
        public int Id { get; set; }
        public int TestId { get; set; }
        public int StudentId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public int ResultId { get; set; }
        public System.Guid AttemptKey { get; set; }
    
        public virtual AttemptResult AttemptResult { get; set; }
        public virtual Student Student { get; set; }
        public virtual TestInstance TestInstance { get; set; }
    }
}
