//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestInstance
    {
        public TestInstance()
        {
            this.TestAttempts = new HashSet<TestAttempt>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int DisciplineType { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<TestAttempt> TestAttempts { get; set; }
    }
}
