// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// StartTeacherRecordedMethod
        /// </summary>
        public void StartTeacherRecordedMethod()
        {
            #region Variable Declarations
            WinEdit uINameEdit = this.UIDebugWindow.UIItemWindow.UITeacherAppexeListItem.UINameEdit;
            #endregion

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit, new Point(39, 10));
        }
        
        /// <summary>
        /// CloseTeacherAppRecordedMethod
        /// </summary>
        public void CloseTeacherAppRecordedMethod()
        {
            #region Variable Declarations
            WinButton uICloseButton = this.UIСетевыеинформационныWindow.UICloseButton;
            #endregion

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(19, 5));
        }
        
        /// <summary>
        /// Проверка главных экранов редактирования вопросов и просмотра результатов
        /// </summary>
        public void BaseViewShowRecordedMethod()
        {
            #region Variable Declarations
            WpfButton uIРедактироватьтестButton = this.UIСетевыеинформационныWindow1.UIItemCustom.UIItemCustom1.UIРедактироватьтестButton;
            WpfButton uIНазадButton = this.UIСетевыеинформационныWindow1.UIItemCustom.UIItemCustom11.UIНазадButton;
            WpfButton uIРезультатыButton = this.UIСетевыеинформационныWindow1.UIItemCustom.UIItemCustom2.UIРезультатыButton;
            #endregion

            // Click 'Редактировать тест' button
            Mouse.Click(uIРедактироватьтестButton, new Point(70, 22));

            // Click 'Назад' button
            Mouse.Click(uIНазадButton, new Point(95, 25));

            // Click 'Результаты' button
            Mouse.Click(uIРезультатыButton, new Point(59, 15));
        }
        
        #region Properties
        public UIDebugWindow UIDebugWindow
        {
            get
            {
                if ((this.mUIDebugWindow == null))
                {
                    this.mUIDebugWindow = new UIDebugWindow();
                }
                return this.mUIDebugWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIСетевыеинформационныWindow UIСетевыеинформационныWindow
        {
            get
            {
                if ((this.mUIСетевыеинформационныWindow == null))
                {
                    this.mUIСетевыеинформационныWindow = new UIСетевыеинформационныWindow();
                }
                return this.mUIСетевыеинформационныWindow;
            }
        }
        
        public UIСетевыеинформационныWindow1 UIСетевыеинформационныWindow1
        {
            get
            {
                if ((this.mUIСетевыеинформационныWindow1 == null))
                {
                    this.mUIСетевыеинформационныWindow1 = new UIСетевыеинформационныWindow1();
                }
                return this.mUIСетевыеинформационныWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIDebugWindow mUIDebugWindow;
        
        private UIItemWindow1 mUIItemWindow;
        
        private UIСетевыеинформационныWindow mUIСетевыеинформационныWindow;
        
        private UIСетевыеинформационныWindow1 mUIСетевыеинформационныWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDebugWindow : WinWindow
    {
        
        public UIDebugWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Debug";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Items View";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UITeacherAppexeListItem UITeacherAppexeListItem
        {
            get
            {
                if ((this.mUITeacherAppexeListItem == null))
                {
                    this.mUITeacherAppexeListItem = new UITeacherAppexeListItem(this);
                }
                return this.mUITeacherAppexeListItem;
            }
        }
        #endregion
        
        #region Fields
        private UITeacherAppexeListItem mUITeacherAppexeListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITeacherAppexeListItem : WinListItem
    {
        
        public UITeacherAppexeListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "TeacherApp.exe";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Context";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32768";
            #endregion
        }
        
        #region Properties
        public UIContextMenu UIContextMenu
        {
            get
            {
                if ((this.mUIContextMenu == null))
                {
                    this.mUIContextMenu = new UIContextMenu(this);
                }
                return this.mUIContextMenu;
            }
        }
        #endregion
        
        #region Fields
        private UIContextMenu mUIContextMenu;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIContextMenu : WinMenu
    {
        
        public UIContextMenu(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Context";
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIRunasadministratorMenuItem
        {
            get
            {
                if ((this.mUIRunasadministratorMenuItem == null))
                {
                    this.mUIRunasadministratorMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIRunasadministratorMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Run as administrator";
                    #endregion
                }
                return this.mUIRunasadministratorMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIRunasadministratorMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIСетевыеинформационныWindow : WinWindow
    {
        
        public UIСетевыеинформационныWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Сетевые информационные технологии";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Сетевые информационные технологии");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Сетевые информационные технологии");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIСетевыеинформационныWindow1 : WpfWindow
    {
        
        public UIСетевыеинформационныWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Сетевые информационные технологии";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Сетевые информационные технологии");
            #endregion
        }
        
        #region Properties
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.UserControl";
            this.WindowTitles.Add("Сетевые информационные технологии");
            #endregion
        }
        
        #region Properties
        public UIItemCustom1 UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new UIItemCustom1(this);
                }
                return this.mUIItemCustom1;
            }
        }
        
        public UIItemCustom11 UIItemCustom11
        {
            get
            {
                if ((this.mUIItemCustom11 == null))
                {
                    this.mUIItemCustom11 = new UIItemCustom11(this);
                }
                return this.mUIItemCustom11;
            }
        }
        
        public UIItemCustom2 UIItemCustom2
        {
            get
            {
                if ((this.mUIItemCustom2 == null))
                {
                    this.mUIItemCustom2 = new UIItemCustom2(this);
                }
                return this.mUIItemCustom2;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom1 mUIItemCustom1;
        
        private UIItemCustom11 mUIItemCustom11;
        
        private UIItemCustom2 mUIItemCustom2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom1 : WpfCustom
    {
        
        public UIItemCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TeacherStartView";
            this.WindowTitles.Add("Сетевые информационные технологии");
            #endregion
        }
        
        #region Properties
        public WpfButton UIРедактироватьтестButton
        {
            get
            {
                if ((this.mUIРедактироватьтестButton == null))
                {
                    this.mUIРедактироватьтестButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIРедактироватьтестButton.SearchProperties[WpfButton.PropertyNames.Name] = "Редактировать тест";
                    this.mUIРедактироватьтестButton.WindowTitles.Add("Сетевые информационные технологии");
                    #endregion
                }
                return this.mUIРедактироватьтестButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIРедактироватьтестButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom11 : WpfCustom
    {
        
        public UIItemCustom11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TeacherFunctionsView";
            this.WindowTitles.Add("Сетевые информационные технологии");
            #endregion
        }
        
        #region Properties
        public WpfButton UIНазадButton
        {
            get
            {
                if ((this.mUIНазадButton == null))
                {
                    this.mUIНазадButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIНазадButton.SearchProperties[WpfButton.PropertyNames.Name] = "Назад";
                    this.mUIНазадButton.WindowTitles.Add("Сетевые информационные технологии");
                    #endregion
                }
                return this.mUIНазадButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIНазадButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom2 : WpfCustom
    {
        
        public UIItemCustom2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TeacherStartView";
            this.WindowTitles.Add("Сетевые информационные технологии");
            #endregion
        }
        
        #region Properties
        public WpfButton UIРезультатыButton
        {
            get
            {
                if ((this.mUIРезультатыButton == null))
                {
                    this.mUIРезультатыButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIРезультатыButton.SearchProperties[WpfButton.PropertyNames.Name] = "Результаты";
                    this.mUIРезультатыButton.WindowTitles.Add("Сетевые информационные технологии");
                    #endregion
                }
                return this.mUIРезультатыButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIРезультатыButton;
        #endregion
    }
}
