//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsoleApplication.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestInstance", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class TestInstance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisciplineTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCurrentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinuteTimeLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisciplineType {
            get {
                return this.DisciplineTypeField;
            }
            set {
                if ((this.DisciplineTypeField.Equals(value) != true)) {
                    this.DisciplineTypeField = value;
                    this.RaisePropertyChanged("DisciplineType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCurrent {
            get {
                return this.IsCurrentField;
            }
            set {
                if ((this.IsCurrentField.Equals(value) != true)) {
                    this.IsCurrentField = value;
                    this.RaisePropertyChanged("IsCurrent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinuteTimeLimit {
            get {
                return this.MinuteTimeLimitField;
            }
            set {
                if ((this.MinuteTimeLimitField.Equals(value) != true)) {
                    this.MinuteTimeLimitField = value;
                    this.RaisePropertyChanged("MinuteTimeLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionCount {
            get {
                return this.QuestionCountField;
            }
            set {
                if ((this.QuestionCountField.Equals(value) != true)) {
                    this.QuestionCountField = value;
                    this.RaisePropertyChanged("QuestionCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatronymicField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupNumber {
            get {
                return this.GroupNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNumberField, value) != true)) {
                    this.GroupNumberField = value;
                    this.RaisePropertyChanged("GroupNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patronymic {
            get {
                return this.PatronymicField;
            }
            set {
                if ((object.ReferenceEquals(this.PatronymicField, value) != true)) {
                    this.PatronymicField = value;
                    this.RaisePropertyChanged("Patronymic");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsoleApplication.ServiceReference.Answer[] AnswersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiyedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsoleApplication.ServiceReference.Answer[] Answers {
            get {
                return this.AnswersField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswersField, value) != true)) {
                    this.AnswersField = value;
                    this.RaisePropertyChanged("Answers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Modifiyed {
            get {
                return this.ModifiyedField;
            }
            set {
                if ((this.ModifiyedField.Equals(value) != true)) {
                    this.ModifiyedField = value;
                    this.RaisePropertyChanged("Modifiyed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Answer", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Answer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiyedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRight {
            get {
                return this.IsRightField;
            }
            set {
                if ((this.IsRightField.Equals(value) != true)) {
                    this.IsRightField = value;
                    this.RaisePropertyChanged("IsRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Modifiyed {
            get {
                return this.ModifiyedField;
            }
            set {
                if ((this.ModifiyedField.Equals(value) != true)) {
                    this.ModifiyedField = value;
                    this.RaisePropertyChanged("Modifiyed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionId {
            get {
                return this.QuestionIdField;
            }
            set {
                if ((this.QuestionIdField.Equals(value) != true)) {
                    this.QuestionIdField = value;
                    this.RaisePropertyChanged("QuestionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ITestSystemService")]
    public interface ITestSystemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestSystemService/GetCurrentTest", ReplyAction="http://tempuri.org/ITestSystemService/GetCurrentTestResponse")]
        TestConsoleApplication.ServiceReference.TestInstance GetCurrentTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestSystemService/GetCurrentTest", ReplyAction="http://tempuri.org/ITestSystemService/GetCurrentTestResponse")]
        System.Threading.Tasks.Task<TestConsoleApplication.ServiceReference.TestInstance> GetCurrentTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestSystemService/RigisterStudent", ReplyAction="http://tempuri.org/ITestSystemService/RigisterStudentResponse")]
        int RigisterStudent(TestConsoleApplication.ServiceReference.Student newStudent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestSystemService/RigisterStudent", ReplyAction="http://tempuri.org/ITestSystemService/RigisterStudentResponse")]
        System.Threading.Tasks.Task<int> RigisterStudentAsync(TestConsoleApplication.ServiceReference.Student newStudent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestSystemService/StartTest", ReplyAction="http://tempuri.org/ITestSystemService/StartTestResponse")]
        System.Guid StartTest(int testId, int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestSystemService/StartTest", ReplyAction="http://tempuri.org/ITestSystemService/StartTestResponse")]
        System.Threading.Tasks.Task<System.Guid> StartTestAsync(int testId, int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestSystemService/GetQuestion4Atempt", ReplyAction="http://tempuri.org/ITestSystemService/GetQuestion4AtemptResponse")]
        TestConsoleApplication.ServiceReference.Question[] GetQuestion4Atempt(int testId, System.Guid atemptKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestSystemService/GetQuestion4Atempt", ReplyAction="http://tempuri.org/ITestSystemService/GetQuestion4AtemptResponse")]
        System.Threading.Tasks.Task<TestConsoleApplication.ServiceReference.Question[]> GetQuestion4AtemptAsync(int testId, System.Guid atemptKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestSystemServiceChannel : TestConsoleApplication.ServiceReference.ITestSystemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestSystemServiceClient : System.ServiceModel.ClientBase<TestConsoleApplication.ServiceReference.ITestSystemService>, TestConsoleApplication.ServiceReference.ITestSystemService {
        
        public TestSystemServiceClient() {
        }
        
        public TestSystemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestSystemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestSystemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestSystemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestConsoleApplication.ServiceReference.TestInstance GetCurrentTest() {
            return base.Channel.GetCurrentTest();
        }
        
        public System.Threading.Tasks.Task<TestConsoleApplication.ServiceReference.TestInstance> GetCurrentTestAsync() {
            return base.Channel.GetCurrentTestAsync();
        }
        
        public int RigisterStudent(TestConsoleApplication.ServiceReference.Student newStudent) {
            return base.Channel.RigisterStudent(newStudent);
        }
        
        public System.Threading.Tasks.Task<int> RigisterStudentAsync(TestConsoleApplication.ServiceReference.Student newStudent) {
            return base.Channel.RigisterStudentAsync(newStudent);
        }
        
        public System.Guid StartTest(int testId, int studentId) {
            return base.Channel.StartTest(testId, studentId);
        }
        
        public System.Threading.Tasks.Task<System.Guid> StartTestAsync(int testId, int studentId) {
            return base.Channel.StartTestAsync(testId, studentId);
        }
        
        public TestConsoleApplication.ServiceReference.Question[] GetQuestion4Atempt(int testId, System.Guid atemptKey) {
            return base.Channel.GetQuestion4Atempt(testId, atemptKey);
        }
        
        public System.Threading.Tasks.Task<TestConsoleApplication.ServiceReference.Question[]> GetQuestion4AtemptAsync(int testId, System.Guid atemptKey) {
            return base.Channel.GetQuestion4AtemptAsync(testId, atemptKey);
        }
    }
}
